# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dpChecker
                                 A QGIS plugin
 Mit diesem Plugin können Dichtheitsprüfungen des Systems Egger in Kombination mit den Attributen der zugehörigen Haltung auf inhaltlich geprüft werden.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-15
        copyright            : (C) 2023 by Armin Matzl
        email                : arminmatzl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dpChecker class from file dpChecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dp_checker import dpChecker
    return dpChecker(iface)
